name: microFrontEnd_app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        app: [shell, dashboard]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.19.0

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      # 🔹 Build each app (parallel via matrix)
      - name: Build App
        run: npm run build ${{ matrix.app }} -- --configuration production

      # 🔹 Run Tests
      - name: Run Tests
        run: npm run test ${{ matrix.app }} -- --watch=false --browsers=ChromeHeadless

      # 🔹 Upload build artifacts
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}-dist
          path: dist/${{ matrix.app }}/
