name: microFrontEnd_app

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      # 🔥 Build BOTH apps
      - name: Build Shell
        run: npm run build shell -- --configuration production --base-href=/microFrontEnd_app/shell/

      - name: Build Dashboard (Remote)
        run: npm run build dashboard -- --configuration production --base-href=/microFrontEnd_app/dashboard/

      # 🔥 Prepare deploy folder
      - name: Prepare Deploy Folder
        run: |
          mkdir deploy
          cp -r dist/shell deploy/shell
          cp -r dist/dashboard deploy/dashboard

      # 🚀 Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
